### ISSUE TITLE
Add example for variable names with multiple words

### ISSUE THREAD

**Issue by r-mueller** [crazyguitar/pysheeet#17]
Regarding https://www.pythonsheets.com/notes/python-basic.html#python-naming-styles.

An example for variable names with compound words would be nice.
For example. Should a method local variable be called `userName` or `user_name`?

**Comment by crazyguitar** [comment]
Based on [PEP8 - Method Names and Instance Variables](https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables)

> Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability.

I think python like under_scope style rather than CamelCase.

CamelCase seems only used by `ClassName` and `TypeVariable` and no `mixedCase `.

**Comment by crazyguitar** [comment]
Oh!! Do you mean add some examples like below?

```python
# good

user_name = 'Guido'

# bad
userName = 'Guido'
```

**Comment by r-mueller** [comment]
Yes this was the idea. I did not know PEP8. And from https://www.pythonsheets.com/notes/python-basic.html#python-naming-styles. it was not clear on how to seperate names in variables. But now i know it is `user_name` :smiley:

**Comment by crazyguitar** [comment]
OK! I will add it later! 👍
