### ISSUE TITLE
make the glossary a bit clearer

### ISSUE THREAD

**Issue by flying-sheep** [crazyguitar/pysheeet#24]
in two cases you do `g = ...` while in once case you want to explain

> calling the generator function returns a generator

and in the other you mean

> `(x for x in seq)` is a generator expression evaluating directly to a generator.

i think you should make this clear.

**Comment by crazyguitar** [comment]
OK! I will ! 

thanks for your recommendation. 👍

**Comment by crazyguitar** [comment]
Do you mind I put your recommendation "quote" in cheat sheet?

**Comment by flying-sheep** [comment]
go ahead!

**Comment by crazyguitar** [comment]
Thank you very much !!!!! 👍 👍 👍 👍 👍
