### ISSUE TITLE
NameError: abort()

### ISSUE THREAD

**Issue by cclauss** [crazyguitar/pysheeet#31]
flake8 testing of https://github.com/crazyguitar/pysheeet on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./app.py:42:21: F821 undefined name 'abort'
    if key is None: abort(404)
                    ^
```

**Comment by crazyguitar** [comment]
Thanks, I have already fixed it. 💯
