### ISSUE TITLE
Translation for korean

### ISSUE THREAD

**Issue by mingrammer** [crazyguitar/pysheeet#40]
How awesome is this!

I wanna spread these great notes to korean, So I would like to translate this into korean after fork.

Are there some rules for translation contributing? And, when I’m done, can I link the korean repository to this README later?

Thank you!

**Comment by crazyguitar** [comment]
Yeah! It's my pleasure.

You can feel free to translate this note into Korean and add the link to README. 👍

**Comment by mingrammer** [comment]
@crazyguitar Thank you for quick response.

I'll start the translation work soon, and when done, I'll send a PR for that. :)

**Comment by crazyguitar** [comment]
👍
