### ISSUE TITLE
mismatch result in page 51

### ISSUE THREAD

**Issue by JerryLauzzz** [crazyguitar/pysheeet#47]
```python
>>> def subgen():
...     try:
...         yield 9527
...      except ValueError:
...          print("get value error")
...
>>> def delegating_gen():
...     yield from subgen()
...
>>> g = delegating_gen()
>>> try:
...     next(g)
...     g.throw(ValueError)
... except StopIteration:
...     print("gen stop")
...
9527
get value error
gen stop
```
in my desktop Python 3.6.2 Anaconda, I run the code above in IPython, but the output dose not contain the first line '9527'.

**Comment by crazyguitar** [comment]
I think the problem is Ipython itself. Ipython does not "show" `output[xx]` when the statement wraps in `try ... except` statement.

If you use cpython shell, the output will contain '9527'.
