### ISSUE TITLE
A better try..except... implementation in C

### ISSUE THREAD

**Issue by damnever** [crazyguitar/pysheeet#5]
https://github.com/drh/cii/blob/master/include/except.h
https://github.com/drh/cii/blob/master/src/except.c

**Comment by crazyguitar** [comment]
Wow! It's amazing!!! :+1::+1::+1:

thanks

**Comment by crazyguitar** [comment]
done!

https://github.com/crazyguitar/pysheeet/blob/master/docs/notes/python-cstyle.rst
