### ISSUE TITLE
Cheatsheet for string manipulations

### ISSUE THREAD

**Issue by heljhumenad** [crazyguitar/pysheeet#88]
Is someone will attend this issue I'm newbie here i just want to learn and someone will mentor me about programming it will much appreciated

**Comment by crazyguitar** [comment]
I will join this issue. You can send pull requests and we can discuss commits together.

By the way, you can try to add your idea to the Unicode cheat sheet. It can not only help you learn how to manipulate strings but also understand the concept of the Unicode.

**Comment by heljhumenad** [comment]
Ok thank you very much appreciated what you do to us 👍

**Comment by heljhumenad** [comment]
How to send a pull request the code will directly to rst files or will make another other code?

**Comment by crazyguitar** [comment]
@heljhumenad 
It seems that the pull request guide is ambiguous. I will fix it lately. 

You can fork this project  and edit docs/notes/pythons-unicode.rst directly. String manipulations should include Unicode considerations, so I think it is uncessary to add a new rst file. After you finish your works, please send a pull request to this project and I will review them. If you have any questions, please feel free to leave your question here.
